### ISSUE TITLE
danger_accept_invalid_certs for tls-rusttls

### ISSUE THREAD

**Issue by meldron** [sbstp/attohttpc#69]
Currently [danger_accept_invalid_certs](https://github.com/sbstp/attohttpc/blob/9d1613e732b20e586fc6a93ede614c7ed34363cf/src/request/builder.rs#L366) is not available for `tls-rusttls`.

I would suggest adding a helper function to easily disable certificate validation for this feature set.

**Comment by adamreichold** [comment]
It is possible to pass this via the `client_config` setting by using `rustls::DangerousClientConfig`, but I guess you are looking for a ready-made implementation of `rustls::ServerCertVerifier` here?

**Comment by meldron** [comment]
@adamreichold yeah would be nice to just have a similar function like with the `tls` feature.

I just looked into how to pass a proper configured `client_config` and right now it looks like i have to add `rustls` and `webpki-roots` in the correct versions to my `cargo.toml` like so:

```toml
rustls = { version = "0.17", features = ["dangerous_configuration"] }
webpki-roots = "0.19.0"
```

and then add something like:

```rust
let mut client_config = ClientConfig::new();

client_config
     .root_store
     .add_server_trust_anchors(&TLS_SERVER_ROOTS);

// still have to find a verifier
let verifiger = MyServerCertVerifierHere;
client_config.dangerous().set_certificate_verifier(verifiger);
```

In my opinion a helper function which just applies the right client_config is way more easier to use for the library user and way less error prone.

**Comment by meldron** [comment]
I think I found an approach:

`cargo.toml`:
```toml
attohttpc = { version = "0.14.0", default-features = false, features = ["tls-rustls", "json"] }
rustls = { version = "0.17", features = ["dangerous_configuration"] }
webpki = "0.21.3"
webpki-roots = "0.19.0"
```

```rust 
use rustls::{ClientConfig, RootCertStore, ServerCertVerified, ServerCertVerifier, TLSError};
use webpki::DNSNameRef;
use webpki_roots::TLS_SERVER_ROOTS;

pub(crate) struct NoVerifier;

impl ServerCertVerifier for NoVerifier {
    fn verify_server_cert(
        &self,
        _roots: &RootCertStore,
        _presented_certs: &[rustls::Certificate],
        _dns_name: DNSNameRef,
        _ocsp_response: &[u8],
    ) -> Result<ServerCertVerified, TLSError> {
        Ok(ServerCertVerified::assertion())
    }
}

pub fn call_danger_accept_invalid_certs(url: &str) -> Result<attohttpc::Response> {
    let mut client_config = ClientConfig::new();

    // add cert store
    client_config
        .root_store
        .add_server_trust_anchors(&TLS_SERVER_ROOTS);

    // disable cert verification
    client_config
        .dangerous()
        .set_certificate_verifier(Arc::new(NoVerifier));

    let response = attohttpc::get(url).client_config(client_config).send()?;

    Ok(response)
}
```

I will try to submit a PR.
